name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6"

      - name: "Install uv"
        uses: "astral-sh/setup-uv@v7"
        with:
          python-version: "3.14"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: "Sync lint dependencies"
        run: uv sync --extra lint

      - name: "Lint"
        run: uv run ruff check .

      - name: "Format"
        run: uv run ruff format . --check
